/* This script can be run via redirection either in Dos or in a Linux/Unix shell. */
/* The purpose of this script is to give you an idea of all the permitted operations and how arguments are passed from the parser to the UT and DM functions. */


/* Create 4 relations */
CREATE STUDENTS (studId='i', studName='c50', studYear='i');
CREATE GRADES (studId='i', studGrade='f');
CREATE GRADES_EXPANDED (studId='i', studGrade='f', minRequested='f');
CREATE STUDENTS_BACKUP (studId='i', studName='c50', studYear='i');

/* Create indexes on the studId fields of the STUDENTS and GRADES relations respectively. */
BUILDINDEX STUDENTS(studId);
BUILDINDEX GRADES(studId);

/* Selection without condition */
SELECT (STUDENTS.studName, STUDENTS.studYear);

/* Selection with simple condition */
SELECT (STUDENTS.studName, STUDENTS.studYear) WHERE STUDENTS.studYear>4;

/* Simple join */
SELECT (STUDENTS.studName, GRADES.studGrade) WHERE STUDENTS.studId=GRADES.studId;

/* Selection without condition and storing the result in a new relation */
SELECT INTO STUDENTS_TEMP (STUDENTS.studName, STUDENTS.studYear);

/* Selection with simple condition and storing the result in a new relation */
SELECT INTO OLDER_STUDENTS (STUDENTS.studName, STUDENTS.studYear) WHERE STUDENTS.studYear>4;

/* Simple join and storing the result in a new relation */
SELECT INTO STUDENTS_GRADES (STUDENTS.studName, GRADES.studGrade) WHERE STUDENTS.studId=GRADES.studId;

/* Simple join between fields of the same relation and storing the result in a new relation */
SELECT INTO GRADES_PASSED (GRADES_EXPANDED.studiD, GRADES_EXPANDED.studGrade) WHERE GRADES_EXPANDED.grade>=GRADES_EXPANDED.minRequested;

/* Deletion without condition */
DELETE STUDENTS;

/* Deletion with simple condition */
DELETE STUDENTS WHERE studYear>4;

/* Deletion of records contained in another relation */
DELETE STUDENTS RECORDS OF STUDENTS_BACKUP;

/* Insertion of a record */
INSERT STUDENTS (studName="Antonis", studYear=5, studId=1023);

/* Insertion of records contained in another relation */
INSERT STUDENTS RECORDS OF STUDENTS_BACKUP;

/* Destruction of original relations */
DESTROY STUDENTS;
DESTROY GRADES;
DESTROY GRADES_EXPANDED;
DESTROY STUDENTS_BACKUP;

/* Destruction of relations constructed in the interim */
DESTROY STUDENTS_TEMP;
DESTROY OLDER_STUDENTS;
DESTROY STUDENTS_GRADES;
DESTROY GRADES_PASSED;

/* Exit */
QUIT;
